spring.application.name=GCPSpannerDemo

server.port=9192

spring.cloud.gcp.spanner.instance-id=test-instance
spring.cloud.gcp.spanner.project-id=test-project
spring.cloud.gcp.spanner.database=test-db
spring.cloud.gcp.spanner.emulator-host=localhost:9010
spring.cloud.gcp.spanner.emulator.enabled=true
spring.jpa.hibernate.ddl-auto=update